# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='channel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='messenger.Channel'),
            preserve_default=False,
        ),
    ]
